<?php

namespace AppBundle\Repository;

/**
 * hobbiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hobbiesRepository extends \Doctrine\ORM\EntityRepository
{
}
